# rustfmt.toml
# arxiv-daily -- version 1
# 
array_width = 20
attr_fn_like_width = 30
blank_lines_lower_bound = 1
blank_lines_upper_bound = 2
chain_width = 20
combine_control_expr = false
empty_item_single_line = false
fn_params_layout = "Vertical"
fn_call_width = 20
force_multiline_blocks = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 60
generated_marker_line_search_limit = 500
format_macro_matchers = true
format_strings = true
imports_layout =  "Vertical"
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
imports_granularity = "Item"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
short_array_element_width_threshold = 5
single_line_if_else_max_width = 0
single_line_let_else_max_width = 0
space_before_colon = false
spaces_around_ranges = true
struct_lit_single_line = false
struct_lit_width = 0
use_small_heuristics = "Off"
max_width = 40
wrap_comments = false
